spring:
  data:
    mongodb:
      uri: mongodb://PharmaCare:Insha20@cluster0-shard-00-00.amtj6.mongodb.net:27017,cluster0-shard-00-01.amtj6.mongodb.net:27017,cluster0-shard-00-02.amtj6.mongodb.net:27017/PatientRecord?ssl=true&replicaSet=atlas-s7v1xt-shard-0&authSource=admin&retryWrites=true&w=majority

server:
  port: 8092

graphql:
  servlet:
    maxQueryDepth: 100
